#!/usr/bin/python3

from src import display
from src import add
import sys
import os

def default():
    print("1. Lancer les tests")
    print("2. Créer un nouveau test")
    print("3. Afficher les tests")
    choice = input()
    if choice == '1': return(0)
    if choice == '2': add.add([""])
    if choice == '3': display.display()

if len(sys.argv) >= 2 : mode = sys.argv[1]
else                  : mode = ""

if mode == "add":
    add.add(sys.argv)
elif mode in ["list","display","show"]:
    display.display()
else :
    while True:
        default()
